module.exports = Object.freeze({
    DB_CONNECTION_STILL_NOT_AVAILABLE: 'DB_CONNECTION_STILL_NOT_AVAILABLE',
    TRACK_NOT_AVAILABLE_MESSAGE: 'No track available',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    OBJECTID_NOT_VALID_FORMAT: 'OBJECTID_NOT_VALID_FORMAT'
});
